version: '3.3'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: stocks
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass UxkR853RadZAkQdk
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: RABBITMQ_ERLANG_COOKIE
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: "12345"
    ports:
      - 5672:5672
      - 15672:15672
