version: '2.0'
services:
    rabbitmq:
        image: rabbitmq:3.8.3-management-alpine
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: RABBITMQ_ERLANG_COOKIE
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: "12345"
        ports:
            - 5672:5672
            - 15672:15672
